name: food_ai

description: FoodAI (NutriGo) — Nutritionix + YandexGPT helper.

publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_dotenv: ^5.0.2
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/keys/
    - .env
